### ISSUE TITLE
Use cast to usize

### ISSUE THREAD

**Issue by bluss** [pyfisch/rust-language-tags#1]
Hi, this is just a tip, I saw your comment on the RFC. As long as you use a simple "C-like" enum, just labels, no contained values in any variant of the enum, then you can cast the enum variants to integers directly. You can use this to implement Ord/Eq much more efficiently.

```rust
enum Example {
 A, B, C
}

fn example() {  let a = Example::A as usize; let b = Example::B as usize; }
```

**Comment by pyfisch** [comment]
Hi, but how should I use a "C-like" enum here? I need an extension variant for unknown or private languages.

**Comment by bluss** [comment]
Maybe you shouldn't. I scanned your source code and it looked like a C-like enum, but I was wrong :(
