### ISSUE TITLE
Use only one allocation 

### ISSUE THREAD

**Issue by Tpt** [pyfisch/rust-language-tags#10]
It would be nice to have just one allocatation per tag like the `url` crate.

I have started to work on it here: https://github.com/Tpt/rudf/blob/master/lib/src/model/language_tag.rs

It provides a full parser that checks if the tag is well-formed" and a work in progress of full validator. I still need to implement the validation against the BCP 47 database. 

If you are interested I could prepare a PR to merge it in your repository.

**Comment by pyfisch** [comment]
I've long planned myself to rewrite this crate to only use a single allocation (like the `url` crate). But I did not get around to do it. I will gladly review a PR implementing this.

Validation against the BCP 47 database is also nice to have.
