### ISSUE TITLE
Figure out what `LanguageTag::extension_subtags` should return

### ISSUE THREAD

**Issue by Tpt** [pyfisch/rust-language-tags#13]
Currently, on the tag "en-r-az-qt" the `LanguageTag::extension_subtags` method returns `[("r", "az"), ("r", "qt")]`. It is not nice at all because the same value would be also returned for "en-r-az-r-qt". We have three options here:
1. Keep the method as it is, retuning `impl Iterator<Type=(&str, &str)>`
2. Make it return `[("r", "az-qt")]` and then, users could call `.split('-')` to get the values of the extensions to get its component (same return type)
3. Make it return `[("r", ["az", "qt"])]` i.e. the type `impl Iterator<Type=(&str, impl Iterator<Type=&str>)>`.

I have a small preference for option 2 that is both correct and let the API users do what they prefer with the value.

**Comment by pyfisch** [comment]
Apparently "en-r-az-r-qt" is an invalid tag according to https://tools.ietf.org/html/bcp47#section-2.2.6 bullet point 3

>    3.  Each singleton subtag MUST appear at most one time in each tag
>        (other than as a private use subtag).  That is, singleton subtags
>        MUST NOT be repeated.  For example, the tag "en-a-bbb-a-ccc" is
>        invalid because the subtag 'a' appears twice.  Note that the tag
>        "en-a-bbb-x-a-ccc" is valid because the second appearance of the
>        singleton 'a' is in a private use sequence.

**Comment by pyfisch** [comment]
PS: I think I also prefer option 2.

**Comment by Tpt** [comment]
#19 implements option 2. "en-r-az-r-qt" is indeed invalid but it is well formed so we should probably handle it properly.
