### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [pyfisch/rust-language-tags#21]
There seem to have been a fair bit of changes in this repo since 0.2.2 but they never made it to a released version.

**Comment by Tpt** [comment]
@AlyoshaVasilieva  I have packaged most of my changes into [oxilangtag](https://github.com/oxigraph/oxilangtag) in case you are interested.

**Comment by pyfisch** [comment]
@AlyoshaVasilieva I think there was some feature I wanted to add before the release, however I didn't get around to it. I've published the current master as v0.3.0 since the mainly the rewrite by @Tpt is a good improvement to the crate.
