### ISSUE TITLE
Normalization of language tags?

### ISSUE THREAD

**Issue by Nutomic** [pyfisch/rust-language-tags#26]
For my use case it would be useful if I could normalize language tags into a common format. What I want to do is receive general `LanguageTag`s through the API (like `en-UK`), but only but only use the language name (`en`) for storage and comparison (because I dont want to deal with too many possible values for now).

I think a good way to implement this would be with a new struct `PrimaryLanguageTag`, which implements the same traits as `LanguageTag` and can be converted back and forth with that type. Then the type checker would ensure that only basic language tags end up in the database, and we cant easily forget the conversion.

**Comment by pyfisch** [comment]
I think for your use case it should be sufficient to call `canonicalize` on a language tag, get the language name with `primary_language` and store this in the database.

Since `PrimaryLanguageTag` is only a thin wrapper around a string I don't think it warrants inclusion in this crate.

**Comment by Nutomic** [comment]
Okay that works for me, thanks!
