### ISSUE TITLE
List of supported Languages?

### ISSUE THREAD

**Issue by Nutomic** [pyfisch/rust-language-tags#32]
For my use case it would be useful if the library could expose a list of all supported languages, so that the user can pick their spoken languages from this list. It should also include the name of each language (without localization, so `es` -> `Español`, `ko` -> `한국어` etc). For now I only care about the primary language.

I couldnt find any library with such a list in a quick search on crates.io, and I think it makes sense to include this here as you already have the list of languages.

**Comment by pyfisch** [comment]
This sounds like a useful feature. I will think about how to best implement it.

**Comment by pyfisch** [comment]
I don't have the time/energy to work on this. However I will review pull-requests for a list of language tags. The languages are already stored in https://github.com/pyfisch/rust-language-tags/blob/master/src/iana_registry.rs and this information shouldn't be duplicated. This file is generated by https://github.com/pyfisch/rust-language-tags/blob/master/scripts/update_from_iana_subtag_registery.py

**Comment by Nutomic** [comment]
Sorry, i have decided to store language definitions differently, not using this crate but directly in the database, which gives us more flexibility. Feel free to close this.
