### ISSUE TITLE
Setters

### ISSUE THREAD

**Issue by bbqsrc** [pyfisch/rust-language-tags#38]
There has been a regression of functionality between 0.2 and 0.3 -- since fields are no longer public, I can no longer mutate the struct and for my use case I need to be able to do that.

If you do not wish for the fields to be public, would it be possible to implement setters (i.e. `set_script`, etc) for the fields?

**Comment by pyfisch** [comment]
Hi, can you describe your use-case in more detail?

If you take a peek at the `LanguageTag` implementation you will notice it is implemented using a single string and a few character pointers. Therefore direct manipulation is difficult. I'd recommend to copy the different segments and construct new tags instead.

**Comment by pyfisch** [comment]
Closed due to inactivity.
