### ISSUE TITLE
Can this crate parse language tag specified in rfc1766?

### ISSUE THREAD

**Issue by NobodyXu** [pyfisch/rust-language-tags#39]
I need to parse language tag specified in [rfc1766](https://datatracker.ietf.org/doc/html/rfc1766) and it seems to be quite similar to language tags shown in the [examples section](https://github.com/pyfisch/rust-language-tags#examples).

**Comment by pyfisch** [comment]
Yes while RFC 1766 has been obsoleted by newer RFCs like RFC 5646 these language tags can still be parsed with this crate.

**Comment by NobodyXu** [comment]
Thanks!
