### ISSUE TITLE
Converting from ISO 639-1 and ISO 639-2

### ISSUE THREAD

**Issue by Uinelj** [pyfisch/rust-language-tags#42]
I'm currently trying to compare language tags from two sources, in different formats that can be considered as being ISO 639-1 and ISO 639-3.
I'm converting these language tags to BCP47 so that I have something standard accross my whole dataset, then test the equality. 

The following code serves as an example:

```rs
        let zh_6391 = LanguageTag::parse("zh");
        let zh_6392 = LanguageTag::parse("zho");
        assert_eq!(zh_6391, zh_6392); //fails
```

While I understand why it fails, I was wondering if there would be some way of converting BCP47 tags into a more canonical form.  I thought that `canonicalize` would help but the test still fails (expectedly). 

I have checked the python library [langcodes](https://github.com/rspeer/langcodes) and it looks that they advise to use two-letter codes (based on the BCP47 spec?), and it seems that the library automagically converts ISO 639-2 into ISO 639-1 when possible, keeping a 3-letter code when not.

```py
zho_6391 = langcodes.Language.get("zho")
zho_6392 = langcodes.Language.get("zh")

assert zho_6391 == zho_6392

print(langcodes.Language.get("lij")) # prints lij
print(langcodes.Language.get("zho")) # prints zh
```

Would such a feature be in the scope of this library? And if so, I'd be glad to try to tackle the problem :)

**Comment by pyfisch** [comment]
The library is pretty much in maintenance mode. Therefore I don't want to add completely new features. However this replacement should be easy to implement on top of the existing language-tags crate.
