### ISSUE TITLE
Shouldn't zh-CN fail to validate?

### ISSUE THREAD

**Issue by pickfire** [pyfisch/rust-language-tags#43]
I don't see `zh-CN` in https://datatracker.ietf.org/doc/html/rfc5646#appendix-A but it seemed to show as pass in test https://github.com/pyfisch/rust-language-tags/blob/e2bcd0ca881f6fc9b8a021f620534acf9f754991/tests/tests.rs#L96.

But browsers like firefox and chromium don't seemed to support the language tag given when I put `zh-CN`, it did not take in the font for `zh` which I have set custom for `zh`, but instead `zh-Hans-CN` and `zh-Hans` works.

I am currently looking for a solution for https://github.com/getzola/zola/issues/2169.

**Comment by pyfisch** [comment]
The tag `zh-CN` is a tag in the format Language-Region expressing "Chinese as written or spoken in China" without mention of a particular script. For a software which wants to pick a font `zh-Hans-CN` conveys more information but the other tag is valid as well.

**Comment by pickfire** [comment]
But browsers (firefox and chrome) doesn't seemed to recognize `zh-CN`. And also, in the real world we differentiate between simplified chinese and traditional chinese, chinese does not mean anything by itself, maybe that's why `zh-CN` is not accepted? Since china can use either simplified chinese or traditional chinese, even though simplified chinese is the officially recognized writing format.

Also, there is no chinese as spoken in china, chinese is a written language, it's not a spoken language, there are dialects for that, the official dialect is mandarin which is widely used in china.

So when we differentiate, for written language we need to specify to say `zh-Hans` and `zh-Hant` since `zh` is not a thing (at least it is a generalization of both writing formats), and for spoken language, there are mandarin (cmn), cantonese (yue), hakka (hak), ... see https://sites.psu.edu/symbolcodes/languages/asia/chinese/ and ISO-639-3.

**Comment by pyfisch** [comment]
> But browsers (firefox and chrome) doesn't seemed to recognize zh-CN.

Browsers only support a small subset of all existing language codes. If you think they should recognize zh-CN file a bug with them. This crate intends to be useful for a wide range of purposes, restricting or changing particular language codes would not fit well with this.

The site you linked even mentions:

> Mandarin Chinese, Simplified Script: zh-Hans is preferred, but zh-CN may be found on older sites.
