### ISSUE TITLE
Deriving Ord for LanguageTag

### ISSUE THREAD

**Issue by raimundomartins** [pyfisch/rust-language-tags#44]
I need to use `LanguageTag` as a key to `BTreeMap`, would it be possible to add `PartialOrd, Ord` to the derive list of that struct?

**Comment by russellbanks** [comment]
To work around this you can create a newtype wrapper that implements PartialOrd and Ord:

```rust
pub struct LanguageTag(language_tags::LanguageTag);

impl PartialOrd for LanguageTag {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for LanguageTag {
    fn cmp(&self, other: &Self) -> Ordering {
        self.as_str().cmp(other.as_str())
    }
}
```

Alternatively, [oxilangtag](https://github.com/oxigraph/oxilangtag) (mentioned under [Related Crates](https://github.com/pyfisch/rust-language-tags#related-crates) in the ReadMe) implements Ord and PartialOrd.

**Comment by raimundomartins** [comment]
I was interested in this particular crate because of example case (de-AT and de), but I can live without it. I'm not fond of the newtype solution for this particular case, it adds too much boilerplate compared to just adding 16 chars to the original crate. In any case, thank you for the solutions, I'll go with the oxilangtag!
