### ISSUE TITLE
Bug in stringification of the language tag

### ISSUE THREAD

**Issue by zbraniecki** [pyfisch/rust-language-tags#8]
Looking at https://github.com/pyfisch/rust-language-tags/blob/a1332c63c2c9b33ab4b84c53947d2b8d6d79e1ae/src/lib.rs#L526

I think there's a bug. If the tag has an empty language subtag, but contains region/script etc. it should serialize to "und-Latn" etc. But if it also contains a private use tag, it should serialize to "und-Latn-x-foo".

Instead of just checking for language subtag, you probably should check if any subtag has been formatted before.

**Comment by pyfisch** [comment]
I don't think this is relevant after the rewrite by @Tpt.
